# Generated by Django 4.2.1 on 2023-05-29 12:32

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('tanks', 'Tanks'), ('healers', 'Healers'), ('damage_dealers', 'Damage Dealers'), ('dealers', 'Dealers'), ('gildmasters', 'Gildmasters'), ('quest_givers', 'Questgivers'), ('blacksmiths', 'Blacksmiths'), ('skiners', 'Skiners'), ('potion_makers', 'Potion makers'), ('spell_masters', 'Spell masters')], max_length=15)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=256)),
                ('text', ckeditor.fields.RichTextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
