# Generated by Django 4.2.1 on 2023-05-30 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0003_alter_post_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
    ]
